// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeToStudy.Models;

namespace TimeToStudy.Migrations
{
    [DbContext(typeof(EventContext))]
    partial class EventContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeToStudy.Models.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EventLength")
                        .HasColumnType("float");

                    b.Property<bool>("Reccuring")
                        .HasColumnType("bit");

                    b.Property<bool>("SetTime")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = "001",
                            EventDescription = "1",
                            EventLabel = "2",
                            EventLength = 3.0,
                            Reccuring = false,
                            SetTime = false
                        },
                        new
                        {
                            Id = "002",
                            EventDescription = "3",
                            EventLabel = "4",
                            EventLength = 5.0,
                            Reccuring = true,
                            SetTime = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
